### ISSUE TITLE
Add page level meta data to sitemap

### ISSUE THREAD

**Issue by thisisrogerflanagan** [thisisrogerflanagan/atterburyworkshop#2]
**Pages**
- Index
- About
- Services

**Meta**
- [ ] name = description
- [ ] property = og:title
- [ ] property = og:type
- [ ] property = og:url
- [ ] property = og:image
- [ ] name = theme-color

**Link**
- [ ] manifest
- [ ] apple-touch-icon
